Exclude pyjslib.py from python3 syntax correction check
pyjs doesn't support python3 and it's unmaintained.
async is a new keyword introduced in python 3.7.

./tests/tools/check_source.sh
Syntax checking using python3 ...
Python 3.7.2+

Syntax error in ./runtime/Worker.py
  File "./svgui/pyjs/lib/pyjslib.py", line 24
    def import_module(path, parent_module, module_name, dynamic=1, async=False):
                                                                       ^
SyntaxError: invalid syntax