Fix crash in runtime if PSK secret is missing
 ./Beremiz_service.py -s $PWD/psk2.txt -n beremiz /tmp/beremiz
Beremiz_service:  1.2-1378c18402c3+

Traceback (most recent call last):
  File "./Beremiz_service.py", line 511, in <module>
    ensurePSK(servicename, PSKpath)
  File "/home/developer/WorkData/PLC/beremiz/beremiz/runtime/Stunnel.py", line 32, in ensurePSK
    PSKgen(ID, PSKpath)
  File "/home/developer/WorkData/PLC/beremiz/beremiz/runtime/Stunnel.py", line 23, in PSKgen
    call(restart_stunnel_cmdline)
  File "/home/developer/WorkData/PLC/beremiz/beremiz/runtime/spawn_subprocess.py", line 116, in call
    pid = posix_spawn.posix_spawnp(cmd[0], cmd)
  File "/home/developer/.local/lib/python2.7/site-packages/posix_spawn/_impl.py", line 120, in posix_spawnp
    return _posix_spawn(lib.posix_spawnp, *args, **kwargs)
  File "/home/developer/.local/lib/python2.7/site-packages/posix_spawn/_impl.py", line 111, in _posix_spawn
    _check_error(res, path)
  File "/home/developer/.local/lib/python2.7/site-packages/posix_spawn/_impl.py", line 10, in _check_error
    raise OSError(errno, os.strerror(errno), path)
OSError: [Errno 2] No such file or directory: '/etc/init.d/S50stunnel'